export interface StudentOffer {
  category: string
  provider: string
  offer: string
  duration: string
  savings: string
  eligibility: string
  verification: string
  notes: string
  link: string
}

export const studentOffers: StudentOffer[] = [
  // Original offers (keeping the good ones, removing duplicates and requested removals)
  {
    category: "Web Design",
    provider: "Webflow",
    offer: "Free CMS website plan (renewable annually)",
    duration: "1 year",
    savings: "$270/year",
    eligibility: "Students worldwide",
    verification: ".edu email and student ID",
    notes: "One site per student. Must re-verify annually.",
    link: "https://webflow.com/education",
  },
  {
    category: "Cloud",
    provider: "Microsoft Azure",
    offer: "$100 in Azure credits",
    duration: "1 year",
    savings: "$100",
    eligibility: "Students in supported countries",
    verification: ".edu email, matching IP/country, no VOIP",
    notes: "Requires valid phone and matching signup location.",
    link: "https://azure.microsoft.com/en-us/free/students/",
  },
  {
    category: "Cloud",
    provider: "Alibaba Cloud",
    offer: "1 vCPU Linux server + Cloud Academy membership",
    duration: "1 year",
    savings: "$152/year",
    eligibility: "Students in Malaysia and Singapore",
    verification: ".edu email",
    notes: "Includes training/certifications. Limited regions.",
    link: "https://www.alibabacloud.com/campaign/education",
  },
  {
    category: "Domains",
    provider: "Namecheap",
    offer: "Free .me domain + TLD discounts",
    duration: "1 year",
    savings: "$10+",
    eligibility: "Select educational institutions",
    verification: ".edu email",
    notes: "Eligibility varies by institution. Check FAQ.",
    link: "https://nc.me/",
  },
  {
    category: "Design",
    provider: "Bootstrap Studio",
    offer: "Free student license + 1 hosted site",
    duration: "1 year",
    savings: "$20",
    eligibility: "Students worldwide",
    verification: ".edu email",
    notes: "Includes one ecommerce-capable hosted site.",
    link: "https://bootstrapstudio.io/student",
  },
  {
    category: "AI/Cloud",
    provider: "Google One AI Premium",
    offer: "Gemini Advanced, NotebookLM, 2TB Drive",
    duration: "2025–2026 academic year",
    savings: "$240/year",
    eligibility: "U.S. university students",
    verification: ".edu email",
    notes: "Sign-up ends June 30, 2025.",
    link: "https://one.google.com/edu",
  },
  {
    category: "AI Coding",
    provider: "Cursor AI",
    offer: "Free Pro plan with premium tokens",
    duration: "1 year",
    savings: "$240/year",
    eligibility: "Students from 43 eligible countries",
    verification: ".edu email",
    notes: "Includes 500 fast requests + unlimited slow tier.",
    link: "https://www.cursor.so/education",
  },
  {
    category: "Design",
    provider: "Figma",
    offer: "Figma Professional plan",
    duration: "2 years",
    savings: "$480",
    eligibility: "Students and educators 13+",
    verification: ".edu email",
    notes: "Includes FigJam, Slides, Dev Studio.",
    link: "https://help.figma.com/hc/en-us/articles/360041061214-Verify-education-status",
  },
  {
    category: "Productivity",
    provider: "Craft.do",
    offer: "AI-powered document editor with real-time collaboration",
    duration: "Renewable yearly",
    savings: "$96/year",
    eligibility: "Students and educators",
    verification: ".edu email or school doc",
    notes: "Note-taking app with GPT-4o integration, 250GB storage, and custom domains.",
    link: "https://www.craft.do/education",
  },
  // Keeping existing offers that weren't marked for removal
  {
    category: "Hosting",
    provider: "InterServer",
    offer: "1 Year Free Hosting Plan",
    duration: "1 year",
    savings: "$30/year",
    eligibility: "U.S. university students only",
    verification: ".edu email",
    notes: "Unlimited websites, SSD storage, 450+ one-click apps, and AI site builder.",
    link: "https://www.interserver.net/webhosting/student-webhosting.html",
  },
  {
    category: "Hosting",
    provider: "Infomaniak Education",
    offer: "Hosting & Productivity Suite",
    duration: "1 year",
    savings: "€87/year (~$94)",
    eligibility: "University or college students",
    verification: "Student ID or institutional email",
    notes: "Web hosting for up to 20 websites, 250GB SSD storage, 250+ SaaS tools.",
    link: "https://www.infomaniak.com/en/education",
  },
  {
    category: "Design",
    provider: "Canva Pro",
    offer: "Canva Pro for Education",
    duration: "1 year",
    savings: "$120/year",
    eligibility: "Students with valid academic status",
    verification: ".edu email",
    notes: "Premium templates, AI tools, team collaboration, and 100+ million assets.",
    link: "https://www.canva.com/education/students/",
  },
  {
    category: "AI Tools",
    provider: "Grok by x.AI",
    offer: "Free API Credits",
    duration: "Monthly",
    savings: "$25/month (~$300/year)",
    eligibility: "Students",
    verification: "x.AI developer portal application",
    notes: "$25 in free API credits monthly for x.AI's LLM interface.",
    link: "https://grok.x.ai",
  },
  {
    category: "Productivity",
    provider: "Zight Pro",
    offer: "Screen Recording",
    duration: "1 year",
    savings: "$96/year",
    eligibility: "Students",
    verification: ".edu email",
    notes: "Screen recording, GIF capturing, video editing, analytics and cloud sharing.",
    link: "https://www.zight.com/education/",
  },
  {
    category: "Security",
    provider: "Dashlane Premium",
    offer: "Password Manager",
    duration: "1 year",
    savings: "$96/year",
    eligibility: "Students",
    verification: "Academic email",
    notes: "Cross-device password manager, secure sharing, VPN, and breach monitoring.",
    link: "https://www.dashlane.com/education",
  },
  {
    category: "Development",
    provider: "JetBrains",
    offer: "Student Pack",
    duration: "1 year",
    savings: "~$360/year",
    eligibility: "High school & university students",
    verification: ".edu email or document",
    notes: "Full access to all JetBrains IDEs (IntelliJ, PyCharm, WebStorm, etc.)",
    link: "https://www.jetbrains.com/community/education/#students",
  },
  {
    category: "Design",
    provider: "D5 Render",
    offer: "3D Visualization Software",
    duration: "1 year",
    savings: "$360/year",
    eligibility: "Students",
    verification: "Academic email",
    notes: "High-speed real-time rendering software for architecture and design.",
    link: "https://www.d5render.com/education",
  },
  {
    category: "Video Editing",
    provider: "Kapwing Pro",
    offer: "AI Video Editing",
    duration: "1 year",
    savings: "$192/year",
    eligibility: "Students",
    verification: ".edu email",
    notes: "AI tools for subtitling, trimming, and video collaboration with no watermark.",
    link: "https://www.kapwing.com/resources/kapwing-education-plan/",
  },
  {
    category: "Engineering",
    provider: "Autodesk Education",
    offer: "Engineering & Design Software including Maya 3D",
    duration: "1 year",
    savings: "$300/year",
    eligibility: "Postsecondary students",
    verification: ".edu email or school docs",
    notes: "Access to AutoCAD, Fusion 360, Revit, Maya 3D, and other CAD tools.",
    link: "https://www.autodesk.com/support/account/manage",
  },
  {
    category: "Development",
    provider: "GitHub",
    offer: "Student Developer Pack",
    duration: "While enrolled",
    savings: "$200,000+ value",
    eligibility: "Students 13+ with academic email",
    verification: ".edu email or student ID",
    notes: "Free access to premium developer tools, cloud credits, and services.",
    link: "https://education.github.com/pack",
  },
  {
    category: "Development",
    provider: "Notion",
    offer: "Notion Pro Plan",
    duration: "While enrolled",
    savings: "$96/year",
    eligibility: "Students and educators",
    verification: ".edu email",
    notes: "Unlimited file uploads, version history, and advanced permissions.",
    link: "https://www.notion.so/product/notion-for-education",
  },
  {
    category: "Project Management",
    provider: "Atlassian",
    offer: "Jira & Confluence",
    duration: "1 year",
    savings: "$70/year",
    eligibility: "Students and academic staff",
    verification: ".edu email",
    notes: "Project management and collaboration tools for up to 10 users.",
    link: "https://www.atlassian.com/software/free",
  },
  {
    category: "Analytics",
    provider: "Tableau",
    offer: "Tableau Desktop",
    duration: "1 year",
    savings: "$840/year",
    eligibility: "Students and instructors",
    verification: ".edu email or academic verification",
    notes: "Professional data visualization and analytics software.",
    link: "https://www.tableau.com/academic/students",
  },
  // NEW OFFERS FROM STEP 4
  {
    category: "Entertainment",
    provider: "Spotify Premium",
    offer: "Spotify Premium with Hulu",
    duration: "1 month free, then $5.99/month",
    savings: "$16/month (usually $21.98)",
    eligibility: "Students",
    verification: "SheerID verification",
    notes: "Spotify Premium ($11.99) + Hulu ($9.99) bundle. Free for first month.",
    link: "https://www.spotify.com/us/student/",
  },
  {
    category: "Productivity",
    provider: "Microsoft Office 365",
    offer: "Free Office 365 for Students",
    duration: "While enrolled",
    savings: "$99/year",
    eligibility: "Students worldwide",
    verification: ".edu email address",
    notes: "Web versions of Outlook, Word, Excel, PowerPoint, OneNote and AI tools.",
    link: "https://www.microsoft.com/en-us/education/products/office",
  },
  {
    category: "Finance",
    provider: "YNAB",
    offer: "Free YNAB for College Students",
    duration: "1 year",
    savings: "$109/year",
    eligibility: "College students",
    verification: "Proof of enrollment document",
    notes: "Personal finance management app with budgeting and expense tracking.",
    link: "https://www.ynab.com/college",
  },
  {
    category: "Survey Tools",
    provider: "Zoho Survey",
    offer: "Survey Plus Plan Upgrade",
    duration: "1 year (extendable)",
    savings: "$204/year",
    eligibility: "Students",
    verification: ".edu email and valid student ID",
    notes: "Advanced survey creation and analytics tools for research projects.",
    link: "https://kzmn7itfur5v8rnz1f7o.lite.vusercontent.net/",
  },
  {
    category: "Survey Tools",
    provider: "SurveyHero",
    offer: "Free Account for Duration of Studies",
    duration: "While enrolled",
    savings: "$300/year",
    eligibility: "Students",
    verification: ".edu email or valid student ID",
    notes: "Unlimited surveys for academic research and projects.",
    link: "https://www.surveyhero.com/students",
  },
  {
    category: "Survey Tools",
    provider: "Jotform",
    offer: "Unlimited Online Surveys",
    duration: "While enrolled",
    savings: "$468/year",
    eligibility: "Students",
    verification: ".edu email and valid student ID",
    notes: "500+ survey templates for academic research and data collection.",
    link: "https://www.jotform.com/surveys/free-survey-for-students/",
  },
  {
    category: "Game Development",
    provider: "Unity",
    offer: "Unity Student Plan",
    duration: "1 year",
    savings: "$185/year",
    eligibility: "Students",
    verification: "SheerID verification",
    notes: "Unity Editor Pro, Odin Inspector and Validator for AR/VR development.",
    link: "https://unity.com/products/unity-student#overview",
  },
  {
    category: "Design",
    provider: "Sketch",
    offer: "Sketch for Education",
    duration: "Lifetime",
    savings: "$240/year (workspace + app)",
    eligibility: "Students and faculty",
    verification: "Valid school documentation",
    notes: "MacOS app and team workspace for life. $10/month workspace + $120 app value.",
    link: "https://www.sketch.com/education/",
  },
  {
    category: "AI Tools",
    provider: "Perplexity Pro",
    offer: "Free Perplexity Pro",
    duration: "2 months (extendable to 2 years)",
    savings: "$40 initial ($480 if extended)",
    eligibility: "Students worldwide",
    verification: ".edu email",
    notes: "Access to premium AI models + $5 API credits monthly. Extendable via affiliate program.",
    link: "https://www.perplexity.ai/backtoschool",
  },
  {
    category: "Engineering",
    provider: "ZW3D",
    offer: "3D CAD Software Student License",
    duration: "300 days",
    savings: "$2,299",
    eligibility: "Students",
    verification: ".edu email address",
    notes: "Professional 3D CAD software for engineering and design projects.",
    link: "https://www.zwsoft.com/product/zw3d/student",
  },
  {
    category: "Entertainment",
    provider: "Amazon Prime",
    offer: "6 Month Free Trial",
    duration: "6 months free, then $7.49/month",
    savings: "$37.45 (6 months)",
    eligibility: "Students",
    verification: "Student verification",
    notes: "Prime Video, free shipping, and other Prime benefits. Usually $14.98/month.",
    link: "https://www.amazon.com/amazonprime?primeCampaignId=studentWlpPrimeRedir",
  },
  {
    category: "Development",
    provider: "Fetch",
    offer: "File Transfer and Sync App",
    duration: "1 year",
    savings: "$28",
    eligibility: "Students",
    verification: ".edu email",
    notes: "Mac file transfer and sync application for development workflows.",
    link: "https://fetchsoftworks.com/fetch/free",
  },
  {
    category: "Hosting",
    provider: "Kickhost",
    offer: "Free Web Hosting",
    duration: "1 year",
    savings: "$8.25",
    eligibility: "Students",
    verification: ".edu email",
    notes: "10GB storage, email, cPanel, SSL, 75+ apps. Spark+ plan features.",
    link: "https://kickhost.com/student-hosting/",
  },
  {
    category: "Design",
    provider: "Axure",
    offer: "Prototyping Software",
    duration: "1 year",
    savings: "$348/year",
    eligibility: "Students",
    verification: "Valid student ID",
    notes: "Professional prototyping and wireframing software for UX/UI design.",
    link: "https://www.axure.com/edu",
  },
  {
    category: "Project Management",
    provider: "Basecamp",
    offer: "Basecamp Pro Unlimited",
    duration: "While enrolled",
    savings: "$349",
    eligibility: "Students",
    verification: ".edu email signup",
    notes: "5TB storage, unlimited projects for team collaboration and project management.",
    link: "https://basecamp.com/discounts",
  },
  {
    category: "Engineering",
    provider: "Altair",
    offer: "AI-Powered Industrial Software Suite",
    duration: "1 year",
    savings: "$685/year",
    eligibility: "Students",
    verification: "Student verification",
    notes: "50+ software bundle for simulation, HPC, data science and AI (Siemens Xcelerator).",
    link: "https://web.altair.com/altair-student-edition",
  },
  {
    category: "Productivity",
    provider: "Lucidchart",
    offer: "Education Account",
    duration: "While enrolled",
    savings: "$108/year",
    eligibility: "Students",
    verification: ".edu email signup",
    notes: "Collaborative diagramming with unlimited object creation for academic projects.",
    link: "https://www.lucidchart.com/pages/usecase/education",
  },
  {
    category: "Development",
    provider: "Bitbucket",
    offer: "Academic License",
    duration: "1 year",
    savings: "$80/year",
    eligibility: "Students",
    verification: ".edu email signup",
    notes: "Code and CI/CD platform with unlimited private repositories for development.",
    link: "https://bitbucket.org/product/education",
  },
  {
    category: "Career",
    provider: "Kickresume",
    offer: "Kickresume Premium",
    duration: "180 days",
    savings: "$27",
    eligibility: "Students",
    verification: "ISIC card or Unidays account",
    notes: "Online resume builder with premium templates and career tools.",
    link: "https://www.kickresume.com/en/students/",
  },
  {
    category: "Development",
    provider: "Tower Pro",
    offer: "Git Client for Mac/Windows",
    duration: "1 year (extendable)",
    savings: "$99/year",
    eligibility: "Students",
    verification: ".edu email address",
    notes: "GUI-based Git client for version control and collaborative development.",
    link: "https://www.git-tower.com/students/mac",
  },
  {
    category: "Project Management",
    provider: "Asana",
    offer: "Asana Starter Account",
    duration: "12 months",
    savings: "$132/year",
    eligibility: "Students worldwide",
    verification: "Goodstack verification",
    notes: "Enterprise project management for assignments and team collaboration.",
    link: "https://asana.com/industry/students",
  },
  {
    category: "3D Design",
    provider: "Lumion Pro",
    offer: "Professional 3D Rendering Software",
    duration: "1 year",
    savings: "€999/year (~$1,080)",
    eligibility: "Students worldwide",
    verification: "Contact worldwide resellers",
    notes: "Real-time 3D rendering for architects, designers, and visualization professionals.",
    link: "https://lumion.com/product/students",
  },
  {
    category: "Collaboration",
    provider: "Miro AI",
    offer: "Education Plan",
    duration: "2 years",
    savings: "$192",
    eligibility: "Students",
    verification: ".edu email and valid ID",
    notes: "AI-integrated collaborative workspace with unlimited boards and Starter Plan perks.",
    link: "https://help.miro.com/hc/en-us/articles/360017730473-Education-plan",
  },
  {
    category: "AI Tools",
    provider: "Anthropic Claude",
    offer: "Free Claude API Credits",
    duration: "Varies",
    savings: "$50+ in API credits",
    eligibility: "Students",
    verification: ".edu email and project explanation",
    notes: "API credits for schoolwork, proof of concepts, and student projects.",
    link: "https://www.anthropic.com/contact-sales/for-student-builders",
  },
  {
    category: "AI Tools",
    provider: "OpenAI",
    offer: "ChatGPT Plus (Limited Regions)",
    duration: "1 month",
    savings: "$20",
    eligibility: "Students in Australia and Colombia",
    verification: "University verification",
    notes: "Limited time offer for select universities in Australia and Colombia only.",
    link: "https://help.openai.com/en/articles/10845652-student-plus-referral-program-australia-colombia",
  },
  {
    category: "Music Production",
    provider: "Suno AI",
    offer: "Suno Pro Music Creation",
    duration: "1 month free, then $5/month",
    savings: "$5/month (50% off)",
    eligibility: "Students",
    verification: ".edu email",
    notes: "AI music maker with 2,500 credits/month (500 songs). Usually $10/month.",
    link: "https://students.suno.com/#students",
  },
]
