export interface StudentOffer {
  category: string
  provider: string
  offer: string
  duration: string
  savings: string
  eligibility: string
  verification: string
  notes: string
  link: string
  image: string
}

export const studentOffers: StudentOffer[] = [
  // Original offers (keeping the good ones, removing duplicates and requested removals)
  {
    category: "Web Design",
    provider: "Webflow",
    offer: "Free CMS website plan (renewable annually)",
    duration: "1 year",
    savings: "$270",
    eligibility: "Students worldwide",
    verification: ".edu email and student ID",
    notes: "One site per student. Must re-verify annually.",
    link: "https://webflow.com/education",
    image: "/logos/webflow.png",
  },
  {
    category: "Cloud",
    provider: "Microsoft Azure",
    offer: "$100 in Azure credits",
    duration: "1 year",
    savings: "$100",
    eligibility: "Students in supported countries",
    verification: ".edu email, matching IP/country, no VOIP",
    notes: "Requires valid phone and matching signup location.",
    link: "https://azure.microsoft.com/en-us/free/students/",
    image: "/logos/microsoft-azure.png",
  },
  {
    category: "Cloud",
    provider: "Alibaba Cloud",
    offer: "1 vCPU Linux server + Cloud Academy membership",
    duration: "1 year",
    savings: "$152",
    eligibility: "Students in Malaysia and Singapore",
    verification: ".edu email",
    notes: "Includes training/certifications. Limited regions.",
    link: "https://www.alibabacloud.com/campaign/education",
    image: "/logos/alibaba-cloud.png",
  },
  {
    category: "Domains",
    provider: "Namecheap",
    offer: "Free .me domain + TLD discounts",
    duration: "1 year",
    savings: "$10+",
    eligibility: "Select educational institutions",
    verification: ".edu email",
    notes: "Eligibility varies by institution. Check FAQ.",
    link: "https://nc.me/",
    image: "/logos/namecheap.png",
  },
  {
    category: "Design",
    provider: "Bootstrap Studio",
    offer: "Free student license + 1 hosted site",
    duration: "1 year",
    savings: "$20",
    eligibility: "Students worldwide",
    verification: ".edu email",
    notes: "Includes one ecommerce-capable hosted site.",
    link: "https://bootstrapstudio.io/student",
    image: "/logos/bootstrap-studio.png",
  },
  {
    category: "AI/Cloud",
    provider: "Google One AI Premium",
    offer: "Gemini 2.5 Pro, Veo 3, Flow, NotebookLM, 2 TB storage, 1,000 monthly AI credits, and much more",
    duration: "While enrolled (Deadline: October 26th 2025)",
    savings: "$240",
    eligibility: "U.S. university students",
    verification: ".edu email",
    notes: "Sign-up ends October 26th 2025. Includes Gemini 2.5 Pro, Veo 3, Flow, NotebookLM, 2 TB storage, 1,000 monthly AI credits, and more.",
    link: "https://one.google.com/edu",
    image: "/logos/google-one-ai-premium.png",
  },
  {
    category: "AI Coding",
    provider: "Cursor AI",
    offer: "Free Pro plan with premium tokens",
    duration: "1 year",
    savings: "$240",
    eligibility: "Students from 43 eligible countries",
    verification: ".edu email",
    notes: "Includes 500 fast requests + unlimited slow tier.",
    link: "https://cursor.com/students",
    image: "/logos/cursor-ai.png",
  },
  {
    category: "Design",
    provider: "Figma",
    offer: "Figma Professional plan",
    duration: "2 years",
    savings: "$480",
    eligibility: "Students and educators 13+",
    verification: ".edu email",
    notes: "Includes FigJam, Slides, Dev Studio.",
    link: "https://help.figma.com/hc/en-us/articles/360041061214-Verify-education-status",
    image: "/logos/figma.png",
  },
  {
    category: "Productivity",
    provider: "Craft.do",
    offer: "AI-powered document editor with real-time collaboration",
    duration: "Renewable yearly",
    savings: "$96",
    eligibility: "Students and educators",
    verification: ".edu email or school doc",
    notes: "Note-taking app with GPT-4o integration, 250GB storage, and custom domains.",
    link: "https://www.craft.do/education",
    image: "/logos/craft-do.png",
  },
  // Keeping existing offers that weren't marked for removal
  {
    category: "Hosting",
    provider: "InterServer",
    offer: "1 Year Free Hosting Plan",
    duration: "1 year",
    savings: "$30",
    eligibility: "U.S. university students only",
    verification: ".edu email",
    notes: "Unlimited websites, SSD storage, 450+ one-click apps, and AI site builder.",
    link: "https://www.interserver.net/webhosting/student-webhosting.html",
    image: "/logos/interserver.png",
  },
  {
    category: "Hosting",
    provider: "Infomaniak Education",
    offer: "Hosting & Productivity Suite",
    duration: "1 year",
    savings: "$94",
    eligibility: "University or college students",
    verification: "Student ID or institutional email",
    notes: "Web hosting for up to 20 websites, 250GB SSD storage, 250+ SaaS tools.",
    link: "https://www.infomaniak.com/en/education",
    image: "/logos/infomaniak-education.png",
  },
  {
    category: "Design",
    provider: "Canva Pro",
    offer: "Canva Pro for Education",
    duration: "1 year",
    savings: "$120",
    eligibility: "Students with valid academic status",
    verification: ".edu email",
    notes: "Premium templates, AI tools, team collaboration, and 100+ million assets.",
    link: "https://www.canva.com/education/students/",
    image: "/logos/canva-pro.png",
  },
  {
    category: "AI Tools",
    provider: "Grok by x.AI",
    offer: "Free API Credits",
    duration: "Monthly",
    savings: "$300",
    eligibility: "Students",
    verification: "x.AI developer portal application",
    notes: "$25 in free API credits monthly for x.AI's LLM interface.",
    link: "https://grok.x.ai",
    image: "/logos/grok.png",
  },
  {
    category: "Productivity",
    provider: "Zight Pro",
    offer: "Screen Recording",
    duration: "1 year",
    savings: "$96",
    eligibility: "Students",
    verification: ".edu email",
    notes: "Screen recording, GIF capturing, video editing, analytics and cloud sharing.",
    link: "https://www.zight.com/education/",
    image: "/logos/zight-pro.png",
  },
  {
    category: "Security",
    provider: "Dashlane Premium",
    offer: "Password Manager",
    duration: "1 year",
    savings: "$96",
    eligibility: "Students",
    verification: "Academic email",
    notes: "Cross-device password manager, secure sharing, VPN, and breach monitoring.",
    link: "https://www.dashlane.com/education",
    image: "/logos/dashlane-premium.png",
  },
  {
    category: "Password Managers",
    provider: "Roboform",
    offer: "Students get 1 year of Roboform Premium",
    duration: "1 year",
    savings: "$30",
    eligibility: "Students",
    verification: ".edu email",
    notes: "Roboform is the next generation password manager.",
    link: "https://www.roboform.com/promotions/college",
    image: "/logos/roboform.png",
  },
  {
    category: "Development",
    provider: "JetBrains",
    offer: "Student Pack",
    duration: "1 year",
    savings: "$360",
    eligibility: "High school & university students",
    verification: ".edu email or document",
    notes: "Full access to all JetBrains IDEs (IntelliJ, PyCharm, WebStorm, etc.)",
    link: "https://www.jetbrains.com/community/education/#students",
    image: "/logos/jetbrains.png",
  },
  {
    category: "Design",
    provider: "D5 Render",
    offer: "3D Visualization Software",
    duration: "1 year",
    savings: "$360",
    eligibility: "Students",
    verification: "Academic email",
    notes: "High-speed real-time rendering software for architecture and design.",
    link: "https://www.d5render.com/education",
    image: "/logos/d5-render.png",
  },
  {
    category: "Video Editing",
    provider: "Kapwing Pro",
    offer: "AI Video Editing",
    duration: "1 year",
    savings: "$192",
    eligibility: "Students",
    verification: ".edu email",
    notes: "AI tools for subtitling, trimming, and video collaboration with no watermark.",
    link: "https://www.kapwing.com/resources/kapwing-education-plan/",
    image: "/logos/kapwing-pro.png",
  },
  {
    category: "Engineering",
    provider: "Autodesk Education",
    offer: "Engineering & Design Software including Maya 3D",
    duration: "1 year",
    savings: "$300",
    eligibility: "Postsecondary students",
    verification: ".edu email or school docs",
    notes: "Access to AutoCAD, Fusion 360, Revit, Maya 3D, and other CAD tools.",
    link: "https://www.autodesk.com/support/account/manage",
    image: "/logos/autodesk-education.png",
  },
  {
    category: "Development",
    provider: "GitHub",
    offer: "Student Developer Pack",
    duration: "While enrolled",
    savings: "$2,000",
    eligibility: "Students 13+ with academic email",
    verification: ".edu email or student ID",
    notes: "Free access to premium developer tools, cloud credits, and services.",
    link: "https://education.github.com/pack",
    image: "/logos/github.png",
  },
  {
    category: "Development",
    provider: "Notion",
    offer: "Notion Pro Plan",
    duration: "While enrolled",
    savings: "$96",
    eligibility: "Students and educators",
    verification: ".edu email",
    notes: "Unlimited file uploads, version history, and advanced permissions.",
    link: "https://www.notion.so/product/notion-for-education",
    image: "/logos/notion.png",
  },
  {
    category: "Project Management",
    provider: "Atlassian",
    offer: "Jira & Confluence",
    duration: "1 year",
    savings: "$70",
    eligibility: "Students and academic staff",
    verification: ".edu email",
    notes: "Project management and collaboration tools for up to 10 users.",
    link: "https://www.atlassian.com/software/free",
    image: "/logos/atlassian.png",
  },
  {
    category: "Analytics",
    provider: "Tableau",
    offer: "Tableau Desktop",
    duration: "1 year",
    savings: "$840",
    eligibility: "Students and instructors",
    verification: ".edu email or academic verification",
    notes: "Professional data visualization and analytics software.",
    link: "https://www.tableau.com/academic/students",
    image: "/logos/tableau.png",
  },
  // NEW OFFERS FROM STEP 4
  {
    category: "Entertainment",
    provider: "Spotify Premium",
    offer: "Spotify Premium with Hulu",
    duration: "1 month free, then $5.99/month",
    savings: "$16",
    eligibility: "Students",
    verification: "SheerID verification",
    notes: "Spotify Premium ($11.99) + Hulu ($9.99) bundle. Free for first month.",
    link: "https://www.spotify.com/us/student/",
    image: "/logos/spotify-premium.png",
  },
  {
    category: "Productivity",
    provider: "Microsoft Office 365",
    offer: "Free Office 365 for Students",
    duration: "While enrolled",
    savings: "$99",
    eligibility: "Students worldwide",
    verification: ".edu email address",
    notes: "Web versions of Outlook, Word, Excel, PowerPoint, OneNote and AI tools.",
    link: "https://www.microsoft.com/en-us/education/products/office",
    image: "/logos/microsoft-office-365.png",
  },
  {
    category: "Finance",
    provider: "YNAB",
    offer: "Free YNAB for College Students",
    duration: "1 year",
    savings: "$109",
    eligibility: "College students",
    verification: "Proof of enrollment document",
    notes: "Personal finance management app with budgeting and expense tracking.",
    link: "https://www.ynab.com/college",
    image: "/logos/ynab.png",
  },
  {
    category: "Infrastructure Design",
    provider: "Bentley Education",
    offer: "50+ professional-grade tools for the infrastructure engineering market, encompassing design, construction, and operation of assets like roads, bridges, buildings, and plants.",
    duration: "While enrolled",
    savings: "$30,000",
    eligibility: "Students",
    verification: ".edu email",
    notes: "Access to Bentley’s complete portfolio of software for infrastructure engineering.",
    link: "https://www.bentley.com/education/",
    image: "/logos/bentley.jpg",
  },
  {
    category: "Survey Tools",
    provider: "Zoho Survey",
    offer: "Survey Plus Plan Upgrade",
    duration: "1 year (extendable)",
    savings: "$204",
    eligibility: "Students",
    verification: ".edu email and valid student ID",
    notes: "Advanced survey creation and analytics tools for research projects.",
    link: "https://kzmn7itfur5v8rnz1f7o.lite.vusercontent.net/",
    image: "/logos/zoho-survey.png",
  },
  {
    category: "Survey Tools",
    provider: "SurveyHero",
    offer: "Free Account for Duration of Studies",
    duration: "While enrolled",
    savings: "$300",
    eligibility: "Students",
    verification: ".edu email or valid student ID",
    notes: "Unlimited surveys for academic research and projects.",
    link: "https://www.surveyhero.com/students",
    image: "/logos/surveyhero.png",
  },
  {
    category: "Survey Tools",
    provider: "Jotform",
    offer: "Unlimited Online Surveys",
    duration: "While enrolled",
    savings: "$468",
    eligibility: "Students",
    verification: ".edu email and valid student ID",
    notes: "500+ survey templates for academic research and data collection.",
    link: "https://www.jotform.com/surveys/free-survey-for-students/",
    image: "/logos/jotform.png",
  },
  {
    category: "Game Development",
    provider: "Unity",
    offer: "Unity Student Plan",
    duration: "1 year",
    savings: "$185",
    eligibility: "Students",
    verification: "SheerID verification",
    notes: "Unity Editor Pro, Odin Inspector and Validator for AR/VR development.",
    link: "https://unity.com/products/unity-student#overview",
    image: "/logos/unity.png",
  },
  {
    category: "Design",
    provider: "Sketch",
    offer: "Sketch for Education",
    duration: "Lifetime",
    savings: "$240",
    eligibility: "Students and faculty",
    verification: "Valid school documentation",
    notes: "MacOS app and team workspace for life. $10/month workspace + $120 app value.",
    link: "https://www.sketch.com/education/",
    image: "/logos/sketch.png",
  },
  {
    category: "AI Tools",
    provider: "Perplexity Pro",
    offer: "Free Perplexity Pro",
    duration: "2 months (extendable to 2 years)",
    savings: "$480",
    eligibility: "Students worldwide",
    verification: ".edu email",
    notes: "Access to premium AI models + $5 API credits monthly. Extendable via affiliate program.",
    link: "https://www.perplexity.ai/backtoschool",
    image: "/logos/perplexity-pro.png",
  },
  {
    category: "Engineering",
    provider: "ZW3D",
    offer: "3D CAD Software Student License",
    duration: "300 days",
    savings: "$2,299",
    eligibility: "Students",
    verification: ".edu email address",
    notes: "Professional 3D CAD software for engineering and design projects.",
    link: "https://www.zwsoft.com/product/zw3d/student",
    image: "/logos/zw3d.png",
  },
  {
    category: "Entertainment",
    provider: "Amazon Prime",
    offer: "Free Trial",
    duration: "Free, then $7.49/month",
    savings: "$37.45",
    eligibility: "Students",
    verification: "Student verification",
    notes: "Prime Video, free shipping, and other Prime benefits. Usually $14.98/month.",
    link: "https://www.amazon.com/amazonprime?primeCampaignId=studentWlpPrimeRedir",
    image: "/logos/amazon-prime.png",
  },
  {
    category: "Development",
    provider: "Fetch",
    offer: "File Transfer and Sync App",
    duration: "1 year",
    savings: "$28",
    eligibility: "Students",
    verification: ".edu email",
    notes: "Mac file transfer and sync application for development workflows.",
    link: "https://fetchsoftworks.com/fetch/free",
    image: "/logos/fetch.jpg",
  },
  {
    category: "Hosting",
    provider: "Kickhost",
    offer: "Free Web Hosting",
    duration: "1 year",
    savings: "$8.25",
    eligibility: "Students",
    verification: ".edu email",
    notes: "10GB storage, email, cPanel, SSL, 75+ apps. Spark+ plan features.",
    link: "https://kickhost.com/student-hosting/",
    image: "/logos/kickhost.png",
  },
  {
    category: "Design",
    provider: "Axure",
    offer: "Prototyping Software",
    duration: "1 year",
    savings: "$348",
    eligibility: "Students",
    verification: "Valid student ID",
    notes: "Professional prototyping and wireframing software for UX/UI design.",
    link: "https://www.axure.com/edu",
    image: "/logos/axure.png",
  },
  {
    category: "Project Management",
    provider: "Basecamp",
    offer: "Basecamp Pro Unlimited",
    duration: "While enrolled",
    savings: "$349",
    eligibility: "Students",
    verification: ".edu email signup",
    notes: "5TB storage, unlimited projects for team collaboration and project management.",
    link: "https://basecamp.com/discounts",
    image: "/logos/basecamp.png",
  },
  {
    category: "Engineering",
    provider: "Altair",
    offer: "AI-Powered Industrial Software Suite",
    duration: "1 year",
    savings: "$685",
    eligibility: "Students",
    verification: "Student verification",
    notes: "50+ software bundle for simulation, HPC, data science and AI (Siemens Xcelerator).",
    link: "https://web.altair.com/altair-student-edition",
    image: "/logos/altair.png",
  },
  {
    category: "Productivity",
    provider: "Lucidchart",
    offer: "Education Account",
    duration: "While enrolled",
    savings: "$108",
    eligibility: "Students",
    verification: ".edu email signup",
    notes: "Collaborative diagramming with unlimited object creation for academic projects.",
    link: "https://www.lucidchart.com/pages/usecase/education",
    image: "/logos/lucidchart.png",
  },
  {
    category: "Development",
    provider: "Bitbucket",
    offer: "Academic License",
    duration: "1 year",
    savings: "$80",
    eligibility: "Students",
    verification: ".edu email signup",
    notes: "Code and CI/CD platform with unlimited private repositories for development.",
    link: "https://bitbucket.org/product/education",
    image: "/logos/bitbucket.png",
  },
  {
    category: "Career",
    provider: "Kickresume",
    offer: "Kickresume Premium",
    duration: "180 days",
    savings: "$27",
    eligibility: "Students",
    verification: "ISIC card or Unidays account",
    notes: "Online resume builder with premium templates and career tools.",
    link: "https://www.kickresume.com/en/students/",
    image: "/logos/kickresume.png",
  },
  {
    category: "Development",
    provider: "Tower Pro",
    offer: "Git Client for Mac/Windows",
    duration: "1 year (extendable)",
    savings: "$99",
    eligibility: "Students",
    verification: ".edu email address",
    notes: "GUI-based Git client for version control and collaborative development.",
    link: "https://www.git-tower.com/students/mac",
    image: "/logos/tower-pro.png",
  },
  {
    category: "Project Management",
    provider: "Asana",
    offer: "Asana Starter Account",
    duration: "12 months",
    savings: "$132",
    eligibility: "Students worldwide",
    verification: "Goodstack verification",
    notes: "Enterprise project management for assignments and team collaboration.",
    link: "https://asana.com/industry/students",
    image: "/logos/asana.png",
  },
  {
    category: "3D Design",
    provider: "Lumion Pro",
    offer: "Professional 3D Rendering Software",
    duration: "1 year",
    savings: "$1,080",
    eligibility: "Students worldwide",
    verification: "Contact worldwide resellers",
    notes: "Real-time 3D rendering for architects, designers, and visualization professionals.",
    link: "https://lumion.com/product/students",
    image: "/logos/lumion-pro.png",
  },
  {
    category: "Collaboration",
    provider: "Miro AI",
    offer: "Education Plan",
    duration: "2 years",
    savings: "$192",
    eligibility: "Students",
    verification: ".edu email and valid ID",
    notes: "AI-integrated collaborative workspace with unlimited boards and Starter Plan perks.",
    link: "https://help.miro.com/hc/en-us/articles/360017730473-Education-plan",
    image: "/logos/miro-ai.png",
  },
  {
    category: "AI Tools",
    provider: "Anthropic Claude",
    offer: "Free Claude API Credits",
    duration: "Varies",
    savings: "$50",
    eligibility: "Students",
    verification: ".edu email and project explanation",
    notes: "API credits for schoolwork, proof of concepts, and student projects.",
    link: "https://www.anthropic.com/contact-sales/for-student-builders",
    image: "/logos/anthropic-claude.png",
  },
  {
    category: "AI Tools",
    provider: "OpenAI",
    offer: "ChatGPT Plus (EXPIRED)",
    duration: "1 month",
    savings: "$20",
    eligibility: "Students in Australia and Colombia",
    verification: "University verification",
    notes: "NOTICE: This offer has expired and is no longer available.",
    link: "https://help.openai.com/en/articles/10845652-student-plus-referral-program-australia-colombia",
    image: "/logos/openai.png",
  },
  {
    category: "Music Production",
    provider: "Suno AI",
    offer: "Suno Pro Music Creation",
    duration: "1 month free, then $5/month",
    savings: "$30",
    eligibility: "Students",
    verification: ".edu email",
    notes: "AI music maker with 2,500 credits/month (500 songs). Usually $10/month.",
    link: "https://students.suno.com/#students",
    image: "/logos/suno-ai.png",
  },
  {
    category: "AI Tools",
    provider: "Manus AI", 
    offer: "1,000 free credits on signup + additional 1,000 credits for referring another student (500 credits for non-student referrals)",
    duration: "Ongoing",
    savings: "$20",
    eligibility: "Students with .edu email",
    verification: ".edu email verification required",
    notes: "AI agent that can do almost anything. Each 1,000 credits normally costs $10 for non-students.",
    link: "https://manus.im/edu",
    image: "/logos/manus-ai.png",
  },
  {
    category: "Design",
    provider: "Spline",
    offer: "Education starter plan for 1 year free (normally $12/month)",
    duration: "1 year",
    savings: "$144",
    eligibility: "Students with valid .edu and university ID",
    verification: ".edu email and university ID required",
    notes: "Breathtaking 3D design studio for creating custom 3D animations that can be exported anywhere.",
    link: "https://spline.design/education",
    image: "/logos/spline.png",
  },
  {
    category: "Engineering",
    provider: "Keycreator CAD",
    offer: "Annual Keycreator CAD Student License equivalent to Keycreator Pro",
    duration: "1 year",
    savings: "$1,485",
    eligibility: "Students worldwide",
    verification: ".edu email address",
    notes: "Precision 2D and 3D CAD software made at the professional level for manufacturing and engineering.",
    link: "https://www.kubotekkosmos.com/schools-students",
    image: "/logos/keycreator.png",
  },
  {
    category: "Engineering",
    provider: "Altium Designer",
    offer: "Altium Student Lab with free annual student license to Altium Designer, Power Analyzer by Keysight, and university coursework",
    duration: "1 year",
    savings: "$2,200",
    eligibility: "Verified university students worldwide",
    verification: ".edu email address + valid student ID",
    notes: "#1 PCB design software in the industry with over 20,000 templates. Includes access to Power Analyzer by Keysight and several university-level coursework and certificates.",
    link: "https://www.altium.com/education/students",
    image: "/logos/altium-designer.png",
  },

  {
    category: "AI Tools",
    provider: "Beautiful.AI",
    offer: "Free pro account for one year",
    duration: "1 year",
    savings: "$144",
    eligibility: "Students worldwide",
    verification: ".edu email",
    notes: "Online presentation maker powered by AI.",
    link: "https://www.beautiful.ai/students",
    image: "/logos/beautiful-ai.png",
  },
  {
    category: "Statistical Analysis",
    provider: "Graphpad Prism",
    offer: "Student license for 1 year",
    duration: "1 year",
    savings: "$142",
    eligibility: "Students worldwide",
    verification: "Photo of valid university ID",
    notes: "A versatile statistics tool purpose-built for scientists-not statisticians.",
    link: "https://www.graphpad.com/how-to-buy/student/",
    image: "/logos/graphpad-prism.png",
  },
  {
    category: "AI Tools",
    provider: "Rayon",
    offer: "Access to the entire Rayon platform which includes 4,000+ CAD blocks and 100+ design templates",
    duration: "While enrolled",
    savings: "$252",
    eligibility: "Students worldwide",
    verification: ".edu email",
    notes: "Rayon is a professional grade software that allows you to create beautiful architectural drawings.",
    link: "https://www.rayon.design/roles/student",
    image: "/logos/rayon.png",
  },
  {
    category: "Design",
    provider: "PTC Creo",
    offer: "Premium license for 1 year",
    duration: "1 year",
    savings: "$3,040",
    eligibility: "Students worldwide",
    verification: ".edu email",
    notes: "Creo is a fully integrated, 3D CAD solution that allows engineers to seamlessly conceptualize, design, analyze, and validate products.",
    link: "https://www.ptc.com/en/education/free-software/creo-university-download",
    image: "/logos/ptc-creo.png",
  },
  {
    category: "Statistical Analysis",
    provider: "JMP",
    offer: "Student license for 1 year",
    duration: "1 year",
    savings: "$1,320",
    eligibility: "Students worldwide",
    verification: ".edu email",
    notes: "Statistical software for dynamic data exploration. Menu-driven interface makes it easy to learn and use – with no coding!",
    link: "https://www.jmp.com/en/academic/jmp-student-edition",
    image: "/logos/jmp.png",
  },
  {
    category: "Design",
    provider: "Affinity Designer",
    offer: "Free lifetime license",
    duration: "Lifetime",
    savings: "$70",
    eligibility: "Students worldwide",
    verification: "Verification through Canva Education",
    notes: "Affinity Designer is an award-winning vector graphics software.",
    link: "https://affinity.serif.com/en-gb/affinity-canva-free-for-schools/#top",
    image: "/logos/affinity_designer.png",
  },
  {
    category: "Design",
    provider: "Affinity Photo",
    offer: "Free lifetime license",
    duration: "Lifetime",
    savings: "$70",
    eligibility: "Students worldwide",
    verification: "Verification through Canva Education",
    notes: "Affinity Photo is an award-winning image editing software.",
    link: "https://affinity.serif.com/en-gb/affinity-canva-free-for-schools/#top",
    image: "/logos/affinity_photo.png",
  },
  {
    category: "Design",
    provider: "Affinity Publisher",
    offer: "Free lifetime license",
    duration: "Lifetime",
    savings: "$70",
    eligibility: "Students worldwide",
    verification: "Verification through Canva Education",
    notes: "Affinity Publisher is the next generation of professional page layout software.",
    link: "https://affinity.serif.com/en-gb/affinity-canva-free-for-schools/#top",
    image: "/logos/affinity_publisher.png",
  },
]